# Algoritmos de otimização - transporte de produtos

In [ ]:
!pip install mlrose

In [ ]:
import mlrose

## Representação do problema

In [ ]:
produtos = [('Refrigerador A', 0.751, 999.90),
            ('Celular', 0.0000899, 2911.12),
            ('TV 55', 0.400, 4346.99),
            ('TV 50', 0.290, 3999.90),
            ('TV 42', 0.200, 2999.00),
            ('Notebook A', 0.00350, 2499.90),
            ('Ventilador', 0.496, 199.90),
            ('Microondas A', 0.0424, 308.66),
            ('Microondas B', 0.0544, 429.90),
            ('Microondas C', 0.0319, 299.29),
            ('Refrigerador B', 0.635, 849.00),
            ('Refrigerador C', 0.870, 1199.89),
            ('Notebook B', 0.498, 1999.90),
            ('Notebook C', 0.527, 3999.00)]
espaco_disponivel = 3

In [ ]:
produtos[0], produtos[0][0], produtos[0][1], produtos[0][2]

(('Refrigerador A', 0.751, 999.9), 'Refrigerador A', 0.751, 999.9)

In [ ]:
def imprimir_solucao(solucao):
  for i in range(len(solucao)):
    if solucao[i] == 1:
      print(f"{produtos[i][0]} - {produtos[i][2]}")

In [ ]:
imprimir_solucao([0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1])

Celular - 2911.12
TV 55 - 4346.99
TV 50 - 3999.9
Ventilador - 199.9
Microondas B - 429.9
Refrigerador B - 849.0
Refrigerador C - 1199.89
Notebook C - 3999.0


In [ ]:
def fitness_function(solucao):
  custo = 0
  soma_espaco = 0
  for i in range(len(solucao)):
    if solucao[i] == 1:
      custo += produtos[i][2]
      soma_espaco += produtos[i][1]
  if soma_espaco > espaco_disponivel:
    custo = 1
  return custo

In [ ]:
fitness_function([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1])

13588.71

In [ ]:
fitness = mlrose.CustomFitness(fitness_function)

In [ ]:
problema = mlrose.DiscreteOpt(length = 14, fitness_fn = fitness, 
                             maximize = True, max_val = 2)

## Hill climb

In [ ]:
melhor_solucao, melhor_custo = mlrose.hill_climb(problema)
melhor_solucao, melhor_custo

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1]), 22993.560000000005)

In [ ]:
imprimir_solucao(melhor_solucao)

Refrigerador A - 999.9
Celular - 2911.12
TV 55 - 4346.99
TV 50 - 3999.9
TV 42 - 2999.0
Notebook A - 2499.9
Ventilador - 199.9
Microondas A - 308.66
Microondas B - 429.9
Microondas C - 299.29
Notebook C - 3999.0


## Simulated annealing

In [ ]:
melhor_solucao, melhor_custo = mlrose.simulated_annealing(problema)
melhor_solucao, melhor_custo

/usr/local/lib/python3.7/dist-packages/mlrose/algorithms.py:311: RuntimeWarning: overflow encountered in exp
  prob = np.exp(delta_e/temp)


(array([0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1]), 22493.65)

In [ ]:
imprimir_solucao(melhor_solucao)

Celular - 2911.12
TV 55 - 4346.99
TV 50 - 3999.9
TV 42 - 2999.0
Microondas A - 308.66
Microondas B - 429.9
Microondas C - 299.29
Refrigerador C - 1199.89
Notebook B - 1999.9
Notebook C - 3999.0


## Algoritmo genético

In [ ]:
melhor_solucao, melhor_custo = mlrose.genetic_alg(problema, pop_size=500, mutation_prob=0.2)
melhor_solucao, melhor_custo

(array([0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1]), 24993.550000000003)

In [ ]:
imprimir_solucao(melhor_solucao)

Celular - 2911.12
TV 55 - 4346.99
TV 50 - 3999.9
TV 42 - 2999.0
Notebook A - 2499.9
Microondas A - 308.66
Microondas B - 429.9
Microondas C - 299.29
Refrigerador C - 1199.89
Notebook B - 1999.9
Notebook C - 3999.0
